import java.awt.event.KeyEvent;
import  java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class DailyEntry extends javax.swing.JFrame {
JFrame frame;
static String driver[] = new String[100];
static String company[] = new String[100];
Set<String> ts;
    /**
     * Creates new form DailyEntry
     */
    public DailyEntry() {
        
       this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        em1 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        em2 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        em3 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        t14 = new javax.swing.JTextField();
        t15 = new javax.swing.JTextField();
        t16 = new javax.swing.JTextField();
        t17 = new javax.swing.JTextField();
        t18 = new javax.swing.JTextField();
        t19 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t23 = new javax.swing.JTextField();
        t27 = new javax.swing.JTextField();
        t28 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        com1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        com = new javax.swing.JTextField();
        par = new javax.swing.JTextField();
        ch = new javax.swing.JTextField();
        vname = new javax.swing.JTextField();
        drv = new javax.swing.JTextField();
        amt = new javax.swing.JTextField();
        vno = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        d1 = new com.toedter.calendar.JDateChooser();

        t3.setBackground(new java.awt.Color(108, 122, 137));
        t3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t3.setForeground(new java.awt.Color(204, 255, 204));
        t3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        em1.setBackground(new java.awt.Color(108, 122, 137));
        em1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        em1.setForeground(new java.awt.Color(204, 255, 204));
        em1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        em1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                em1ActionPerformed(evt);
            }
        });

        t4.setBackground(new java.awt.Color(108, 122, 137));
        t4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t4.setForeground(new java.awt.Color(204, 255, 204));
        t4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel13.setBackground(new java.awt.Color(236, 240, 241));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(236, 240, 241));
        jLabel13.setText("Particulars:");

        jLabel14.setBackground(new java.awt.Color(236, 240, 241));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(236, 240, 241));
        jLabel14.setText("Company:");

        jLabel15.setBackground(new java.awt.Color(236, 240, 241));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 240, 241));
        jLabel15.setText("Date:");

        jLabel16.setBackground(new java.awt.Color(236, 240, 241));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(236, 240, 241));
        jLabel16.setText("Challan No:");

        jLabel17.setBackground(new java.awt.Color(236, 240, 241));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(236, 240, 241));
        jLabel17.setText("Vehicle No:");

        jLabel18.setBackground(new java.awt.Color(236, 240, 241));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(236, 240, 241));
        jLabel18.setText("Driver:");

        jLabel19.setBackground(new java.awt.Color(236, 240, 241));
        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(236, 240, 241));
        jLabel19.setText("Amount:");

        jLabel20.setBackground(new java.awt.Color(236, 240, 241));
        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(236, 240, 241));
        jLabel20.setText("Vehicle Name:");

        t5.setBackground(new java.awt.Color(108, 122, 137));
        t5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t5.setForeground(new java.awt.Color(204, 255, 204));
        t5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(em1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(t5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                .addGap(47, 47, 47))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(em1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));

        em2.setBackground(new java.awt.Color(108, 122, 137));
        em2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        em2.setForeground(new java.awt.Color(204, 255, 204));
        em2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        em2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                em2ActionPerformed(evt);
            }
        });

        t6.setBackground(new java.awt.Color(108, 122, 137));
        t6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t6.setForeground(new java.awt.Color(204, 255, 204));
        t6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel21.setBackground(new java.awt.Color(236, 240, 241));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(236, 240, 241));
        jLabel21.setText("Particulars:");

        jLabel22.setBackground(new java.awt.Color(236, 240, 241));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(236, 240, 241));
        jLabel22.setText("Company:");

        jLabel23.setBackground(new java.awt.Color(236, 240, 241));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(236, 240, 241));
        jLabel23.setText("Date:");

        jLabel24.setBackground(new java.awt.Color(236, 240, 241));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(236, 240, 241));
        jLabel24.setText("Challan No:");

        jLabel25.setBackground(new java.awt.Color(236, 240, 241));
        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(236, 240, 241));
        jLabel25.setText("Vehicle No:");

        jLabel26.setBackground(new java.awt.Color(236, 240, 241));
        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(236, 240, 241));
        jLabel26.setText("Driver:");

        jLabel27.setBackground(new java.awt.Color(236, 240, 241));
        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(236, 240, 241));
        jLabel27.setText("Amount:");

        jLabel28.setBackground(new java.awt.Color(236, 240, 241));
        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(236, 240, 241));
        jLabel28.setText("Vehicle Name:");

        t7.setBackground(new java.awt.Color(108, 122, 137));
        t7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t7.setForeground(new java.awt.Color(204, 255, 204));
        t7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t6, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(em2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(t7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                .addGap(47, 47, 47))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(em2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        em3.setBackground(new java.awt.Color(108, 122, 137));
        em3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        em3.setForeground(new java.awt.Color(204, 255, 204));
        em3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        em3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                em3ActionPerformed(evt);
            }
        });

        t13.setBackground(new java.awt.Color(108, 122, 137));
        t13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t13.setForeground(new java.awt.Color(204, 255, 204));
        t13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        t14.setBackground(new java.awt.Color(108, 122, 137));
        t14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t14.setForeground(new java.awt.Color(204, 255, 204));
        t14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        t15.setBackground(new java.awt.Color(108, 122, 137));
        t15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t15.setForeground(new java.awt.Color(204, 255, 204));
        t15.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        t16.setBackground(new java.awt.Color(108, 122, 137));
        t16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t16.setForeground(new java.awt.Color(204, 255, 204));
        t16.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t16ActionPerformed(evt);
            }
        });

        t17.setBackground(new java.awt.Color(108, 122, 137));
        t17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t17.setForeground(new java.awt.Color(204, 255, 204));
        t17.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        t18.setBackground(new java.awt.Color(108, 122, 137));
        t18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t18.setForeground(new java.awt.Color(204, 255, 204));
        t18.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        t19.setBackground(new java.awt.Color(108, 122, 137));
        t19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t19.setForeground(new java.awt.Color(204, 255, 204));
        t19.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        t1.setBackground(new java.awt.Color(108, 122, 137));
        t1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t1.setForeground(new java.awt.Color(204, 255, 204));
        t1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        t23.setBackground(new java.awt.Color(108, 122, 137));
        t23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t23.setForeground(new java.awt.Color(204, 255, 204));
        t23.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        t27.setBackground(new java.awt.Color(108, 122, 137));
        t27.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t27.setForeground(new java.awt.Color(204, 255, 204));
        t27.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        t28.setBackground(new java.awt.Color(108, 122, 137));
        t28.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t28.setForeground(new java.awt.Color(204, 255, 204));
        t28.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButton2.setBackground(new java.awt.Color(34, 167, 240));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Create Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        com1.setBackground(new java.awt.Color(108, 122, 137));
        com1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        com1.setForeground(new java.awt.Color(204, 255, 204));
        com1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextField3.setText("jTextField1");

        jButton4.setBackground(new java.awt.Color(34, 167, 240));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(240, 240, 240));
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(46, 49, 49));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Enter Daily Data:");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 298, 60));

        Close.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Close.setForeground(new java.awt.Color(240, 240, 240));
        Close.setText("X");
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        jPanel1.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 31, 60));

        Minimize.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Minimize.setForeground(new java.awt.Color(240, 240, 240));
        Minimize.setText("-");
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 34, 39));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 80));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(236, 240, 241));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Particulars:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 167, 46));

        jLabel6.setBackground(new java.awt.Color(236, 240, 241));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Company:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 149, 50));

        jLabel8.setBackground(new java.awt.Color(236, 240, 241));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Challan No:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, 46));

        jLabel9.setBackground(new java.awt.Color(236, 240, 241));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("Vehicle No:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 166, 169, 60));

        jLabel10.setBackground(new java.awt.Color(236, 240, 241));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Driver:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 120, 46));

        jLabel11.setBackground(new java.awt.Color(236, 240, 241));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("Amount:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 141, 46));

        jLabel12.setBackground(new java.awt.Color(236, 240, 241));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setText("Vehicle Name:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 193, 46));

        com.setBackground(new java.awt.Color(108, 122, 137));
        com.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        com.setForeground(java.awt.Color.white);
        com.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        com.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comKeyReleased(evt);
            }
        });
        jPanel2.add(com, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 210, 40));

        par.setBackground(new java.awt.Color(108, 122, 137));
        par.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        par.setForeground(java.awt.Color.white);
        par.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        par.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parActionPerformed(evt);
            }
        });
        jPanel2.add(par, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 510, 40));

        ch.setBackground(new java.awt.Color(108, 122, 137));
        ch.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        ch.setForeground(java.awt.Color.white);
        ch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(ch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 230, 40));

        vname.setBackground(new java.awt.Color(108, 122, 137));
        vname.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        vname.setForeground(java.awt.Color.white);
        vname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(vname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 210, 40));

        drv.setBackground(new java.awt.Color(108, 122, 137));
        drv.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        drv.setForeground(java.awt.Color.white);
        drv.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        drv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                drvKeyReleased(evt);
            }
        });
        jPanel2.add(drv, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 230, 40));

        amt.setBackground(new java.awt.Color(108, 122, 137));
        amt.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        amt.setForeground(java.awt.Color.white);
        amt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 230, 40));

        vno.setBackground(new java.awt.Color(108, 122, 137));
        vno.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        vno.setForeground(java.awt.Color.white);
        vno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(vno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 210, 40));

        jButton3.setBackground(new java.awt.Color(34, 167, 240));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setText("Back");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 157, 49));

        jLabel29.setBackground(new java.awt.Color(236, 240, 241));
        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(236, 240, 241));
        jLabel29.setText("Date:");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 36, 78, 50));

        jButton5.setBackground(new java.awt.Color(34, 167, 240));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(240, 240, 240));
        jButton5.setText("Save");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 157, 49));

        d1.setBackground(new java.awt.Color(204, 255, 204));
        d1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        d1.setForeground(new java.awt.Color(204, 255, 204));
        d1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel2.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 210, 43));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1020, 520));

        setSize(new java.awt.Dimension(1020, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
       if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to close","Close",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
				{ this.dispose();}
    }//GEN-LAST:event_CloseMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void em1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_em1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_em1ActionPerformed

    private void em2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_em2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_em2ActionPerformed

    private void em3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_em3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_em3ActionPerformed

    private void t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t16ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String d,m,y,co,vn,vno1,a,c,dr,cno;
       SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        String dt = sdf.format(d1.getDate());
        c=com.getText();
        co=par.getText();
        vn=vname.getText();
        vno1=vno.getText();
        a=amt.getText();
        cno=ch.getText();
        dr=drv.getText();
        
        int flag1=0,flag2=0;
        try
        {
            int x;
            String comp[] = new String[100];
            String drvv[] = new String[100];
            String co1=com.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/MyApp","root","sourya");
            Statement s = con.createStatement();
            ResultSet rs1 = s.executeQuery("Select * from company");
            ResultSet rs2 = s.executeQuery("Select * from driver");
            int i=0;
            while(rs1.next())
            { i++;
                comp[i]=(String)rs1.getString(1);
                if(co1.contentEquals(comp[i]))
                flag1=1;
            }
            i=0;
            while(rs2.next())
            { i++;
                drvv[i]=(String)rs2.getString(1);
                if(dr.contentEquals(drvv[i]))
                flag2=1;
            } 
            con.close();
        }
        catch(Exception ex) { System.out.println(ex);  }

        if(dt.contentEquals("")||co.contentEquals("")||vn.contentEquals("")||
            vno1.contentEquals("")||a.contentEquals("")||c.contentEquals("")||dr.contentEquals(""))
        {         JOptionPane.showMessageDialog(null,"Fields are Empty","Login Error",JOptionPane.ERROR_MESSAGE); }

        else if( flag1==1  )
        JOptionPane.showMessageDialog(null,"Company does not Exists,  Please Register","Login Error",JOptionPane.ERROR_MESSAGE);

        else if( flag2==1  )
        JOptionPane.showMessageDialog(null,"Driver does not Exists,  Please Register","Login Error",JOptionPane.ERROR_MESSAGE);

        else
        {
            try{
                int x;
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/MyApp","root","sourya");
                Statement s = con.createStatement();
                x = s.executeUpdate("Insert into data values('"+dt+"','"+c+"','"+co+"','"+cno+"','"+dr+"','"+vn+"','"+vno1+"',"+a+");");
                if(x!=0)
                {
                    JOptionPane.showMessageDialog(null,"Registered Successfully","Registration",JOptionPane.INFORMATION_MESSAGE);}
                com.setText(null);
                d1.setDate(null);
                par.setText(null);
                vname.setText(null);
                vno.setText(null);
                amt.setText(null);
                ch.setText(null);
                drv.setText(null);
                con.close();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Homepage1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void drvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_drvKeyReleased
        try
        {
            int x;
            ts = new TreeSet<String>();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/MyApp","root","sourya");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("Select * from driver");
            int i=0;
            while(rs.next())
            { i++;
                driver[i]=(String)rs.getString(1);
                ts.add(driver[i]);
            }
            con.close();
        }
        catch(Exception ex) { System.out.println(ex);  }

        if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getKeyCode()==KeyEvent.VK_DELETE  ||  evt.getKeyCode()==KeyEvent.KEY_PRESSED)
        {  }
        else
        {
            String str = drv.getText();
            int l=str.length();
            for(String data:ts)
            {
                String test="";
                for(int i=0;i<l;i++)
                {
                    if(l<=data.length())
                    test=test+data.charAt(i);
                }
                if(test.equalsIgnoreCase(str))
                {      drv.setText(data);
                    drv.setSelectionStart(l);
                    drv.setSelectionEnd(data.length());
                    break;
                }
            }
        }

    }//GEN-LAST:event_drvKeyReleased

    private void comKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comKeyReleased
        try
        {
            int x;
            ts = new TreeSet<String>();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/MyApp","root","sourya");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("Select * from company");
            int i=0;
            while(rs.next())
            { i++;
                company[i]=(String)rs.getString(1);
                ts.add(company[i]);
            }
            con.close();
        }
        catch(Exception ex) { System.out.println(ex);  }

        if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getKeyCode()==KeyEvent.VK_DELETE)
        {

        }
        else
        {
            String str = com.getText();
            int l=str.length();
            for(String data:ts)
            {
                String test="";
                for(int i=0;i<l;i++)
                {
                    if(l<=data.length())
                    test=test+data.charAt(i);
                }
                if(test.equalsIgnoreCase(str))
                {      com.setText(data);
                    com.setSelectionStart(l);
                    com.setSelectionEnd(data.length());
                    break;
                }
            }
        }

    }//GEN-LAST:event_comKeyReleased

    private void parActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DailyEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DailyEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DailyEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DailyEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DailyEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Minimize;
    private javax.swing.JTextField amt;
    private javax.swing.JTextField ch;
    private javax.swing.JTextField com;
    private javax.swing.JTextField com1;
    private com.toedter.calendar.JDateChooser d1;
    private javax.swing.JTextField drv;
    private javax.swing.JTextField em1;
    private javax.swing.JTextField em2;
    private javax.swing.JTextField em3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField par;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextField t17;
    private javax.swing.JTextField t18;
    private javax.swing.JTextField t19;
    private javax.swing.JTextField t23;
    private javax.swing.JTextField t27;
    private javax.swing.JTextField t28;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField vname;
    private javax.swing.JTextField vno;
    // End of variables declaration//GEN-END:variables
}
